languageCode = "en"
hasCJKLanguage = true
enableEmoji = true
title = "叉鸽的博客 | MrCroxx's Blog"
theme = "DoIt"

[author]
name = "叉鸽 | MrCroxx"
email = "mrcroxx@outlook.com"
link = "/posts/about"

[params]
version = "0.2.X"
description = "Welcome to MrCroxx's Blog."

[params.search]
enable = true
type = "lunr"
contentLength = 4_000
placeholder = ""
maxResultLength = 10
snippetLength = 50
highlightTag = "em"
absoluteURL = false

[params.search.algolia]
index = ""
appID = ""
searchKey = ""

[params.header]
desktopMode = "fixed"
mobileMode = "auto"

[params.header.title]
logo = ""
name = "叉鸽 | MrCroxx"
pre = ""
post = ""
typeit = true

[params.footer]
enable = true
custom = ""
hugo = true
copyright = true
author = true
since = 2_019
icp = ""
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'

[params.section]
paginate = 20
dateFormat = "01-02"
rss = 10

[params.page]
hiddenFromHomePage = false
hiddenFromSearch = false
twemoji = true
lightgallery = true
ruby = true
fraction = true
fontawesome = true
linkToMarkdown = true
rssFullText = false

[params.page.toc]
enable = true
keepStatic = false
auto = true

[params.page.code]
copy = true
maxShownLines = 10_000

[params.page.comment]
enable = false

[params.page.math]
enable = true
blockLeftDelimiter = ""
blockRightDelimiter = ""
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
copyTex = true
mhchem = true

[params.home]
rss = 10

[params.home.profile]
enable = true
gravatarEmail = ""
avatarURL = "/avatar.jpg"
title = "叉鸽 | MrCroxx"
subtitle = "Welcome to MrCroxx's blog."
typeit = true
social = true
disclaimer = ""

[params.home.posts]
enable = true
paginate = 10

[params.social]
twitter = "CroxxMr"
email = "mrcroxx@outlook.com"
douban = "mrcroxx"
rss = true
[params.social.github]
id = "MrCroxx"
[params.social.github.icon]
class = "fab fa-github fa-fw"


[outputs]
home = ["HTML", "RSS", "JSON"]

[[menu.main]]
identifier = "posts"
pre = ""
post = ""
name = "文章 | Archives"
url = "/posts/"
title = ""
weight = 1

[[menu.main]]
identifier = "categories"
pre = ""
post = ""
name = "分类 | Categories"
url = "/categories/"
title = ""
weight = 2

[[menu.main]]
identifier = "tags"
pre = ""
post = ""
name = "标签 | Tags"
url = "/tags/"
title = ""
weight = 3

[[menu.main]]
identifier = "about"
pre = ""
post = ""
name = "关于我 | About"
url = "/posts/about"
title = ""
weight = 4

[markup.tableOfContents]
startLevel = 2
endLevel = 4

[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
unsafe = true
