# baseURL: ${BaseURL}
defaultContentLanguage: zh-cn
languageCode: zh-CN
hasCJKLanguage: true
enableEmoji: true
title: 叉鸽 MrCroxx 的博客
theme: LoveIt
author:
  name: 叉鸽
  email: mrcroxx@outlook.com
  link: about
params:
  version: 0.2.X
  description: "Welcome to MrCroxx's Blog."
  search:
    enable: true
    type: lunr
    contentLength: 4000
    placeholder: ""
    maxResultLength: 10
    snippetLength: 50
    highlightTag: em
    absoluteURL: false
    algolia:
      index: ""
      appID: ""
      searchKey: ""
  header:
    desktopMode: fixed
    mobileMode: auto
    title:
      logo: ""
      name: 叉鸽 | MrCroxx
      pre: ""
      post: ""
      typeit: true
  footer:
    enable: true
    custom: ""
    hugo: true
    copyright: true
    author: true
    since: 2019
    icp: ""
    license: '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
  section:
    paginate: 20
    dateFormat: 01-02
    rss: 10
  page:
    hiddenFromHomePage: false
    hiddenFromSearch: false
    twemoji: true
    lightgallery: true
    ruby: true
    fraction: true
    fontawesome: true
    linkToMarkdown: true
    rssFullText: false
    toc:
      enable: true
      keepStatic: false
      auto: true
    code:
      copy: true
      maxShownLines: 10000
    comment:
      enable: false
      gitalk:
        enable: true
        owner: MrCroxx
        repo: mrcroxx.github.io
        clientId: cea7c74a1c09d447d6bc
        clientSecret: 5ee9349a6af24ec56fbe5f545f858adb4fe0a1a7
    math:
      enable: true
      blockLeftDelimiter: ""
      blockRightDelimiter: ""
      inlineLeftDelimiter: ""
      inlineRightDelimiter: ""
      copyTex: true
      mhchem: true
  home:
    rss: 10
    profile:
      enable: true
      gravatarEmail: ""
      avatarURL: /avatar.jpg
      title: 叉鸽 | MrCroxx
      subtitle: "Welcome to MrCroxx's blog."
      typeit: true
      social: true
      disclaimer: ""
    posts:
      enable: true
      paginate: 5
  social:
    GitHub: mrcroxx
    Email: mrcroxx@outlook.com
    Zhihu: mrcroxx
    Douban: mrcroxx
    RSS: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - 
      identifier: posts
      pre: ""
      post: ""
      name: 所有文章
      url: /posts/
      title: ""
      weight: 1
    - 
      identifier: categories
      pre: ""
      post: ""
      name: 分类
      url: /categories/
      title: ""
      weight: 2
    - 
      identifier: tags
      pre: ""
      post: ""
      name: 标签
      url: /tags/
      title: ""
      weight: 3
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 4
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
